start "ui" cmd.exe /k "npm run start -w=ui"
start "server-main" cmd.exe /k "npm run main -w=node_servers"
start "server-metadata" cmd.exe /k "npm run metadata -w=node_servers"
start "server-text" cmd.exe /k "cd text_server && mix run --no-halt"
start "server-weather" cmd.exe /k "weather_server/env/Scripts/Activate.bat && python3 -m ./weather_server"
start "server-body" cmd.exe /k "body_server/env/Scripts/Activate.bat && python3 -m ./body_server"
start "server-style" cmd.exe /k "style_server/env/Scripts/Activate.bat && python3 -m ./style_server"
start "server-people" cmd.exe /k "cd ./people_server/build/bin && ./peopleServer.exe"
